service: challengue

frameworkVersion: '3'

plugins:
  - serverless-auto-swagger
  - serverless-offline
  - serverless-esbuild
  - serverless-stage-manager
  - serverless-deployment-bucket

custom:
  base: ${self:service}-${self:provider.stage}
  #ESBUILD
  esbuild:
    bundle: true
    minify: true
  #ALLOWED STAGES
  stages:
    - develop
    - staging
    - prod
  #TABLE NAME
  tableName: ${self:custom.base}-characters
  #DOCUMENTATION
  autoswagger:
    typefiles: ['./src/types/response.d.ts','./src/types/error.d.ts','./src/types/request.d.ts']
    basePath: /${self:provider.stage}


provider:
  name: aws
  runtime: nodejs14.x
  stage: ${opt:stage, 'develop'}
  region: ${opt:region, 'us-east-1'}
  timeout: 15
  deploymentBucket:
    name: ${self:custom.base}
    serverSideEncryption: AES256
  environment:
    TABLE_NAME: ${self:custom.tableName}
  iam:
    role:
      statements:
        - Effect: Allow
          Action: # Gives permission to DynamoDB tables in a specific region
            - dynamodb:Query
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:BatchGetItem
            - dynamodb:DeleteItem
          Resource:
            - arn:aws:dynamodb:${aws:region}:${aws:accountId}:table/${self:custom.tableName}
            - arn:aws:dynamodb:${aws:region}:${aws:accountId}:table/${self:custom.tableName}/index/*

functions:
  - ${file(./config/functions.yml)}
resources:
  - ${file(./config/database.yml)}
