export const API_URL = 'https://swapi.dev/api';

export const REST = {
  SUCCESS: 'OK',
  INTERNAL: 'INTERNAL_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  BAD_REQUEST: 'BAD_REQUEST',
  CREATED: 'CREATED',
  CONFLICT: 'CONFLICT',
};

export const STATUS_CODE = {
  SUCCESS: 200,
  INTERNAL: 500,
  NOT_FOUND: 404,
  BAD_REQUEST: 400,
  CREATED: 201,
  CONFLICT: 409,
};

export const CHARACTER_ENTITY = 'PERSONAJE';
