get-characters:
  description: GET characters
  handler: src/api/get-characters.handler
  events:
    - http:
        path: /characters
        method: get
        responseData:
          200:
            description: Success
            bodyType: ResponseList
          404:
            description: Not found
            bodyType: ErrorNotFound
          500:
            description: Internal Error
            bodyType: ErrorInternal
        queryStringParameters:
          search:
            type: string
            description: Name of the character
          page:
            type: integer
            description: Page number
get-character:
  description: GET character
  handler: src/api/get-character.handler
  events:
    - http:
        path: /characters/{id}
        method: get
        responseData:
          200:
            description: Success
            bodyType: Response
          400:
            description: Bad request
            bodyType: ErrorBadRequest
          404:
            description: Not found
            bodyType: ErrorNotFound
          500:
            description: Internal Error
            bodyType: ErrorInternal
post-character: 
  description: POST character
  handler: src/api/post-character.handler
  events:
    - http:
        path: /characters
        method: post
        bodyType: Request
        responseData:
          201:
            description: Created
            bodyType: ResponseCreated
          400:
            description: Bad request
            bodyType: ErrorBadRequest
          409:
            description: Already created
            bodyType: ErrorConflict
          500:
            description: Internal Error
            bodyType: ErrorInternal
get-characters-db:
  description: GET characters from DB
  handler: src/api/get-characters-db.handler
  events:
    - http:
        path: /charactersdb
        method: get
        responseData:
          200:
            description: Success
            bodyType: ResponseList
          404:
            description: Not found
            bodyType: ErrorNotFound
          500:
            description: Internal Error
            bodyType: ErrorInternal